### ISSUE TITLE
Video creating dashboard HIFI

### ISSUE THREAD

**Issue by Taye-Taiwo** [zuri-training/Colflick-Team119#10]

**Comment by Pello26** [comment]
Desktop 
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=412%3A2


Mobile

https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=412%3A2

**Comment by Pello26** [comment]
Video creator screen desktop

https://www.figma.com/proto/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1423%3A14424&scaling=scale-down&page-id=412%3A3&starting-point-node-id=1263%3A11236&show-proto-sidebar=1

**Comment by Pello26** [comment]
Upload screen

https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1588%3A13937

**Comment by Pello26** [comment]
User profile video screen

https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1588%3A13937

**Comment by Pello26** [comment]
User about screen

https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1588%3A13937

**Comment by Pello26** [comment]
mobile video creator screen 

https://www.figma.com/proto/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1359%3A14581&scaling=scale-down&page-id=412%3A3&starting-point-node-id=1326%3A10911&show-proto-sidebar=1

**Comment by Pello26** [comment]
mobile upload screen

https://www.figma.com/proto/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1359%3A14717&scaling=scale-down&page-id=412%3A3&starting-point-node-id=1326%3A10911&show-proto-sidebar=1

**Comment by Pello26** [comment]
mobile user profile video sceen

https://www.figma.com/proto/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1359%3A14658&scaling=scale-down&page-id=412%3A3&starting-point-node-id=1326%3A10911&show-proto-sidebar=1

**Comment by Pello26** [comment]
Upload screen desktop

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A63007&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A61551&show-proto-sidebar=1

**Comment by Pello26** [comment]
user video sceen

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A63021&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A61551&show-proto-sidebar=1
