### ISSUE TITLE
Homepage HIFI

### ISSUE THREAD

**Issue by Taye-Taiwo** [zuri-training/Colflick-Team119#11]
Input your figma link here when done

**Comment by Temilola007** [comment]
**Home page Mobile view:** 
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1307%3A10993
**Desktop view:**
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1307%3A10857

**Comment by Temilola007** [comment]
**Home page Mobile view:**
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1307%3A10993
**Desktop view:**
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1307%3A10857
**User side-drop menu**
https://www.figma.com/file/ygjIMrn9ekgcEVCC0hRh3w/Team-119-team-library?node-id=1419%3A12307

**Comment by Temilola007** [comment]
**Homepage mobile prototype screen:**
https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A61704&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A61851&show-proto-sidebar=1
**Side menu screen:**
https://www.figma.com/file/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A61887
**Homepage desktop prototype screen:**
https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A61567&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1%3A61551&show-proto-sidebar=1
