### ISSUE TITLE
Comment section page HIFI

### ISSUE THREAD

**Issue by Taye-Taiwo** [zuri-training/Colflick-Team119#17]
Input your figma link under the comment section

**Comment by Temilola007** [comment]
**Comment section screen(mobile only):**
https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A65268&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A61851&show-proto-sidebar=1
