### ISSUE TITLE
Settings pages HIFI

### ISSUE THREAD

**Issue by Taye-Taiwo** [zuri-training/Colflick-Team119#18]
Input your figma link under the comment section

**Comment by CarrieRogue** [comment]
Settings Screens for Mobile https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A62148&starting-point-node-id=1%3A61851

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A62263&starting-point-node-id=1%3A61851

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A63262&starting-point-node-id=1%3A61851

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A62472&starting-point-node-id=1%3A61851

**Comment by CarrieRogue** [comment]
Settings Screens for Desktop 
https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=5%3A68668&starting-point-node-id=1%3A61551&scaling=scale-down

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A63889&starting-point-node-id=1%3A61551&scaling=scale-down

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=1%3A63676&starting-point-node-id=1%3A61551&scaling=scale-down

https://www.figma.com/proto/ciCBrvYhrcIrp6X7aUlNjy/TEAM-119?node-id=5%3A68581&starting-point-node-id=1%3A61551&scaling=scale-down
